### ISSUE TITLE
python@3.8.2: hash check failed

### ISSUE THREAD

**Issue by uniquis** [ScoopInstaller/Main#1049]
Error occured at
```
Checking hash of python-3.8.2-amd64.exe ... ERROR Hash check failed!
App:         main/python
URL:         https://www.python.org/ftp/python/3.8.2/python-3.8.2-amd64.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    d9309423b693ed63aea6b1fbfc0c34f16842cdca22a1b3edef283b87567a53b9
Actual:      8e400e3f32cdcb746e62e0db4d3ae4cba1f927141ebc4d0d5a4006b0daee8921
```

**Comment by Ash258** [comment]
Cannot reproduce

Are you sure your scoop is up to date?
Please run `scoop update; scoop uninstall python; scoop install python`

Hash mismatch could be caused by these factors:

- Network error
- Antivirus configuration
- Site is blocked (Great Firewall of China, Corporate restrictions, ...)

![A](https://i.imgur.com/7KjDunD.png)
