### ISSUE TITLE
busybox package should not shim in `rm.exe`

### ISSUE THREAD

**Issue by fluffynuts** [ScoopInstaller/Main#1112]
see https://github.com/rmyorston/busybox-w32/issues/187: the busybox rm.exe invocation only works correctly under the busybox shell. Installing this as the globally-available instance of rm produces unexpected results for the user.

**Comment by imgx64** [comment]
And if possible, I'd like an option to install busybox without any shims at all (apart from `busybox.exe`, obviously). If I want to run a busybox command from cmd, I don't mind typing `busybox base64` instead of `base64` for example.

The problem I'm facing is that it clobbers many other more-powerful utilities that I installed separately (`file`, `awk`, `wget`, etc), and I don't want to run `scoop reset foo` for each and every one of them.

Adding a `busybox-only` manifest, similar to [git-with-openssh](https://github.com/ScoopInstaller/Main/blob/master/bucket/git-with-openssh.json) would be ideal.

**Comment by rasa** [comment]
It seems busybox has solved this problem in https://github.com/rmyorston/busybox-w32/commit/f41697493de1a25d0f56930d81cf9560172ce7b7

**Comment by fluffynuts** [comment]
I was just about to add that :D
