### ISSUE TITLE
Add .exe to some of the executables. Better for WSL.

### ISSUE THREAD

**Issue by urwrstkn8mare** [ScoopInstaller/Main#1295]
Sorry if the title was a little ambiguous. 
![image](https://user-images.githubusercontent.com/42769125/89021398-0f42be00-d353-11ea-8ea6-b1d3311f0699.png)
As you can see 7z's executable has an extension of '.exe'. However, concfg doesn't. While this makes no difference for Windows, in WSL since you can access the Windows' path if I typed concfg it would try to launch the executable (WSL can run windows executables). The solution is to add '.exe' which means I would have to concfg.exe to run it from WSL and at that point I'm fully aware I'm running a windows command. Like if I ran notepad.exe from WSL. I ran into this problem when I tried to use the say command in WSL. It's available in Mac OS's UNIX based environment so I thought I would try it out but it started putting out Windows errors and I got very confused leading me down a rabbit hole but eventually, I found this. I've manually changed it myself in the shims folder. But I'm proposing to make sure that executables for each app are required to have '.exe' at the end (it makes no difference). That would be great thanks for taking the time to read.

**Comment by ret394** [comment]
this is a good idea. but it's likely to not attract much attention due to technical reasons. But I maybe wrong.

The Windows errors are confusing, but that's different topic.

Having file extensions is always a benefit. In all OS's. But be careful if you express such not-mainstream ideas like this idea publicly on any website or forum. Here be angry mobs.

But, I am really sure you can use the ps1 version with powershell and the cmd version with command prompt/cmd. They just call the actual binary(concfg file without extensions) and provid convenience.

This is the solution the project came up with, and with the state of things, it's good enough.

thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)

**Comment by urwrstkn8mare** [comment]
Thanks for that info!

**Comment by rasa** [comment]
Sounds good. Can this issue be closed?
