### ISSUE TITLE
add dotnet framework and powershell modules

### ISSUE THREAD

**Issue by MichielVanwelsenaere** [ScoopInstaller/Main#13]
Hi,

I wan't to automate my setup a bit further and would like to automate setting up:
- [dotnet framework](https://dotnet.microsoft.com/download/dotnet-framework)
- [Az Powershell module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-1.8.0)

Do you think this is possible, could you point me to some sample manifests?
Az Powershell requires dotnet framework 4.7.2 minimum, any idea if it's possible to use `depends` to verify for a minimum version somehow?

Thanks!

**Comment by Ash258** [comment]
I am looking into experimenting with dotnet frameworks Ash258/scoop-Ash258#19

It should be possible same way as there is vcredists packages.
I should have time this weekend to inpect.

**Comment by niheaven** [comment]
ref: https://docs.microsoft.com/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#find-net-framework-versions-45-and-later-in-the-registry

MS recommands using registry to get .Net versions.

**Comment by nuno-andre** [comment]
You can get the latest version that verifies that condition with:

    (gp "hklm:software\microsoft\net framework setup\ndp\v*\full").version |
        ? { $_ -ge [version]"4.7.2" } | select -last 1

(without the last segment (`\full`) for PS < 4.5)

But I warn you (since Microsoft doesn't) that Az Powershell is not as bloated as Azure Powershell (e.g. I had to reinstall Azure Powershell because it's yet not possible to manage an OAuth2 On-Behalf-Of flow for App Services).

I think the best approach is to keep Azure Powershell for PS5.1 (i.e. Windows Powershell -`powershell.exe`- which requires .NET Framework) and install Az Powershell as module of PS6 (i.e. Powershell Core -`pwsh.exe`- which doesn't).
