### ISSUE TITLE
ffmpeg@4.3.1: download via aria2 failed

### ISSUE THREAD

**Issue by moigagoo** [ScoopInstaller/Main#1459]

**Comment by SharakPL** [comment]
It fails because [ffmpeg.zeranoe.com closed on September 18th](https://www.reddit.com/r/ffmpeg/comments/ikht2k/ffmpegzeranoecom_will_close_on_sep_18_2020/). We need another source...

@r15ch13 have you picked one already? These look fine https://github.com/BtbN/FFmpeg-Builds/releases but there's so many available with different licenses I'm not sure which to choose.

**Comment by moigagoo** [comment]
https://github.com/BtbN/FFmpeg-Builds/releases are daily automatically build packages, I can't see a way to use those with Scoop. There is no unique URL for a given version. Instead, there're dozens of packages built every now and then for the same FFmpeg version.

The other source mentioned at https://ffmpeg.org/download.html, https://www.gyan.dev/ffmpeg/builds/, won't do either since there are only 64 bit versions there. Its package naming suffers from the same problem as the first source one.

After a quick search, I couldn't find an alternative package source 😩

**Comment by moigagoo** [comment]
OK, this looks promising: https://www.videohelp.com/software/ffmpeg

32 bit: https://www.videohelp.com/download/ffmpeg-4.3.1-win32-static.zip
64 bit: https://www.videohelp.com/download/ffmpeg-4.3.1-win64-static.zip

**Comment by moigagoo** [comment]
Submitted a PR: https://github.com/ScoopInstaller/Main/pull/1464

**Comment by SharakPL** [comment]
> 
> 
> https://github.com/BtbN/FFmpeg-Builds/releases are daily automatically build packages, I can't see a way to use those with Scoop. There is no unique URL for a given version. Instead, there're dozens of packages built every now and then for the same FFmpeg version.
> 
> The other source mentioned at https://ffmpeg.org/download.html, https://www.gyan.dev/ffmpeg/builds/, won't do either since there are only 64 bit versions there. Its package naming suffers from the same problem as the first source one.
> 
> After a quick search, I couldn't find an alternative package source 😩

@BtbN [faced that problem](https://github.com/BtbN/FFmpeg-Builds/issues/4#issue-712051489) and came up with this https://github.com/BtbN/FFmpeg-Builds/wiki/Latest. I think it's worth a try to implement in Scoop since you wouldn't need to update ffmpeg.json anymore. We just need to pick the right version for this.

**Comment by GyanD** [comment]
@moigagoo 

What kind of 'package naming' are you looking for?

And how many of your users require 32-bit builds?

**Comment by moigagoo** [comment]
> What kind of 'package naming' are you looking for?

I was looking for the kind of naming that would uniquely point a single URL to a single version and a single architecture of the package. Daily builds have hashes in their names, so there's no one URL I can put in the json file.

> And how many of your users require 32-bit builds?

Does it matter? Scoop provides 64 and 32 bit packages whenever possible, post packages have those two flavors.

**Comment by GyanD** [comment]
> 
> > What kind of 'package naming' are you looking for?
> 
> I was looking for the kind of naming that would uniquely point a single URL to a single version and a single architecture of the package. Daily builds have hashes in their names, so there's no one URL I can put in the json file.

The URLs on the page itself are static and version-agnostic and will remain so, e.g. https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z.  If you wish to hard-code a link, these are suitable.

When such links are accessed, agents are redirected to the latest versioned build of that variant so the file downloaded (at present) is ffmpeg-4.3.1-2020-10-01-full_build.7z. IMHO, it is not suitable to keep the generic name above for the packages themselves.

> > And how many of your users require 32-bit builds?
> 
> Does it matter? Scoop provides 64 and 32 bit packages whenever possible, post packages have those two flavors.

In my and most other builds, ffmpeg links with many third-party dependencies. Many of these no longer support 32-bit compilation. And a separate environment has to be maintained to setup a 32-bit toolchain. Given the specific nature of what ffmpeg does, it is very unusual in 2020 to be using a 32-bit limited-feature build. Indeed, my builds' download count is in six figures and I've had only one request for 32-bit. BtbN also doesn't plan to [support](https://github.com/BtbN/FFmpeg-Builds/issues/3#issuecomment-699619319) it.

**Comment by moigagoo** [comment]
@GyanD OK, got it, you're right. I'll close my PR then since there's a better one pending.

**Comment by SharakPL** [comment]
@GyanD I think the problem with this solution of just one hard coded link is that you wouldn't be able to update package on scoop. It wouldn't show any update since the url would be always the same. Auto builds with different names are also problematic, since they're done twice a day and most of the time contain exactly the same version as before, so ffmpeg.json would have to be constantly updated just to provide empty useless update. What is required is a descriptive link to valid package that is build after new version of ffmpeg comes out and so you could simply update version number and hash in source url.

**Comment by GyanD** [comment]
Can you scrape HTML? On the page, there are two elements. One has `id="git-version"` and other with `id="release-version"`. When the strings in these elements change, the builds have been updated.

Let's call the strings encapsulated as X and Y respectively. The filenames are `ffmpeg-X-full_build.7z`..etc for the git builds and `ffmpeg-Y-full_build.7z`..etc for the release builds. The direct links are in the packages folder relative to my site, but I prefer avoiding direct access, if you can.
