### ISSUE TITLE
git-filter-repo@2.34.0: requires lifted privileges

### ISSUE THREAD

**Issue by EtiamNullam** [ScoopInstaller/Main#3638]
## Bug Report

**Package Name:** git-filter-repo

### Current Behaviour

Package fails to install (error at unpack) because of symbolic links included if not run with lifted privileges:

```
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\user\scoop\apps\git-filter-repo\2.34.0\git-filter-repo-2.34.0\contrib\filter-repo-demos\filter-branch-ish
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\user\scoop\apps\git-filter-repo\2.34.0\git-filter-repo-2.34.0\git_filter_repo.py
```

### Expected Behaviour

Package should install without a need for lifted privileges.

### Additional context/output

Using `7-zip` directly also gives the same error, unless running `7-zip` as Administrator.

Same problem:

https://superuser.com/questions/1076527/7zip-cannot-create-symbolic-link-access-is-denied-to-libhdfs-so-and-libhadoop-s

### Possible Solution

Maybe instead of counting on symbolic links included in the `.tar` archive we should create shims on our own?

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1320

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-06-01T13:52:34.0746932+02:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by issaclin32** [comment]
Can you run `7z` and tell me which 7-zip are you using?

I tried to reproduce the issue, but extraction and symlinks worked fine.

I was testing on Win10 / Powershell5 with both `21.06` and `21.07` versions of 7-zip.

related issue: https://github.com/ScoopInstaller/Scoop/issues/4647

**Comment by EtiamNullam** [comment]
> Could you run `7z` and tell me which 7-zip are you using?

Sorry, my bad for not including the full log from 7zip. It's version `21.07` installed through scoop:

```
7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

Scanning the drive for archives:
1 file, 190207 bytes (186 KiB)

Extracting archive: C:\Users\user\scoop\apps\git-filter-repo\2.34.0\v2.34.0.zip
--
Path = C:\Users\user\scoop\apps\git-filter-repo\2.34.0\v2.34.0.zip
Type = zip
Physical Size = 190207
Comment = 235fed326910a90b3322bc535d643a9003f8d7e1


Sub items Errors: 2

Archives with Errors: 1

Sub items Errors: 2
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\user\scoop\apps\git-filter-repo\2.34.0\git-filter-repo-2.34.0\contrib\filter-repo-demos\filter-branch-ish
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\user\scoop\apps\git-filter-repo\2.34.0\git-filter-repo-2.34.0\git_filter_repo.py
```

**Comment by rashil2000** [comment]
The issue is with the latest version of 7zip. See the above linked Scoop core issue for more details

**Comment by issaclin32** [comment]
**7-zip 19.00** can extract the file without showing any error, but the symlink would not be handled properly.

For example, `$dir\git_filter_repo.py` should be a symbolic link that points to `$dir\git_filter_repo`, but when we use 7-zip 19.00, it becomes a text file that contains the following text:
```
git_filter_repo
```

In this case, the package will not work properly, unless we copy/rename `$dir\git_filter_repo` as `$dir\git_filter_repo.py`.

This is actually quite troublesome, because there are more files that uses *symlinks* other than `$dir\git_filter_repo.py`, and we can not be sure that there won't be more symlink added to the file in the future.

I think the real solution is to see if there is a way to filter out those **"failing" symlinks** after extracting with 7-zip 19.00, and fix the in `pre_install`.
