### ISSUE TITLE
Krew plugin manager KREW_ROOT env must be compatible with bin path

### ISSUE THREAD

**Issue by bkmeneguello** [ScoopInstaller/Main#3784]
## Bug Report

krew

### Current Behaviour

`kubectl krew list` shows a warning `To be able to run kubectl plugins, you need to add the
"%%USERPROFILE%%\.krew\bin" directory to your PATH environment variable
and restart your shell.`

### Expected Behaviour

The command should be able to [find the bin dir](https://github.com/kubernetes-sigs/krew/blob/0b910c846768d1b60afa13edb544fd8fcd23d200/cmd/krew/cmd/internal/setup_check.go#L59) in the path.

### Possible Solution

The problem is the environment variable `KREW_ROOT` being set with `$persist_dir` instead of the `$dir` variable, which points to the path relative to the `bin` dir

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.5

**Additional software:**

#### Scoop Configuration

not relevant

**Comment by tech189** [comment]
Could you re-open your terminal window and run `$env:PATH`? After installing, I had to open a new window to get `~\scoop\apps\krew\current\.krew\bin` to show up in my PATH.

But yes, I get the same warning even when it is in my PATH. If I move the `.krew` folder to `%USERPROFILE%` rather than the Scoop installation location and update the PATH I get the same warning.

It seems to function when it is in either location (tested krew help, list, update, install) but only if you run with `sudo`. Does it function for you too?

**Comment by tech189** [comment]
Correction: you’re right - the warning disappears when `KREW_ROOT` is set to `…\current\.krew` rather than the `$persist_dir`. However, it was set like that when the app was first added to Scoop so I’m reluctant to change it as there’s probably a reason for using it rather than `$dir` (perhaps to make sure that plugins were persisted when Scoop updated krew itself).

@jamezrin would it be okay to change this env variable? In my testing, reinstalling krew does not lose data if I set the variable to `$dir`, but maybe I’m missing something.

**Comment by jamezrin** [comment]
> Correction: you’re right - the warning disappears when `KREW_ROOT` is set to `…\current\.krew` rather than the `$persist_dir`. However, it was set like that when the app was [first added to Scoop](https://github.com/ScoopInstaller/Main/pull/3144) so I’m reluctant to change it as there’s probably a reason for using it rather than `$dir` (perhaps to make sure that plugins were persisted when Scoop updated krew itself).
> 
> @jamezrin would it be okay to change this env variable? In my testing, reinstalling krew does not lose data if I set the variable to `$dir`, but maybe I’m missing something.

Hey, to be honest, I don't remember the details of this, but I think it makes sense to change the env to `$dir` if that makes it work.

**Comment by tech189** [comment]
Thanks! I've made the change so the warning should be gone now. Just reinstall krew to get the updated environment variable.
