### ISSUE TITLE
7zip@23.00: decompress error

### ISSUE THREAD

**Issue by rbharathkumar** [ScoopInstaller/Main#4799]
Hi Team, Got the below error while trying to update 7zip.

```powershell
scoop update *
7zip: 22.01 -> 23.00
Updating one outdated app:
Updating '7zip' (22.01 -> 23.00)
Downloading new version
Loading 7z2300-x64.msi from cache
Checking hash of 7z2300-x64.msi ... ok.
Uninstalling '7zip' (22.01)
Installing '7zip' (23.00) [64bit] from main bucket
Loading 7z2300-x64.msi from cache
Extracting 7z2300-x64.msi ... ERROR Exit code was 1625!
Failed to extract files from C:\<DIR1 WITH SPACE IN NAME>\<DIR2 WITH SPACE IN NAME>\Scoop\apps\7zip\23.00\7z2300-x64.msi.
Log file:
  C:\<DIR1 WITH SPACE IN NAME>\<DIR2 WITH SPACE IN NAME>\Scoop\apps\7zip\23.00\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4023.00%3a+decompress+error
```

Thank you for all the hard work...

**Comment by rbharathkumar** [comment]
As #4786, setting the config flag `use_lessmsi` to `true` installs `lessmsi` and resolves the issue ?
Can anyone confirm ? Maybe lessmsi can be added as a dependency for 7zip ?

**Comment by HUMORCE** [comment]
https://learn.microsoft.com/en-us/windows/win32/msi/error-codes

**Comment by HUMORCE** [comment]
Sorry, I had to close this issue for now. because this is a general issue with Scoop, or MSIEXEC.

- Reboot or sign out then re-login
- `scoop config USE_LESSMSI true`, some manifests will fail to extract with lessmsi, at which point you can turn it off(false). 
- Manually resolving msiexec processes that hang in the background
- etc.

See also: https://github.com/ScoopInstaller/Scoop/issues/4559
