### ISSUE TITLE
[Bug]: Not able to update pip after installing python

### ISSUE THREAD

**Issue by zd-dalibor** [ScoopInstaller/Main#5226]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

python

### Expected/Current Behaviour

When the pip upgrade command is executed:
```pwsh
python -m pip install --upgrade pip
```
I am getting this error (`{user}` is placeholder for real username}:
```txt
Requirement already satisfied: pip in c:\users\{user}\scoop\apps\python\current\lib\site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl.metadata
  Using cached pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
  WARNING: Failed to write executable - trying to use .deleteme logic
  Rolling back uninstall of pip
  Moving to c:\users\{user}\scoop\persist\python\lib\site-packages\pip-23.2.1.dist-info\
   from C:\Users\{user}\scoop\persist\python\Lib\site-packages\~ip-23.2.1.dist-info
  Moving to c:\users\{user}\scoop\persist\python\lib\site-packages\pip\
   from C:\Users\{user}\scoop\persist\python\Lib\site-packages\~ip
  Moving to c:\users\{user}\scoop\persist\python\scripts\
   from C:\Users\{user}\scoop\persist\python\~cripts
ERROR: Could not install packages due to an OSError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\{user}\\scoop\\apps\\python\\current\\Scripts\\pip.exe' -> 'C:\\Users\\{user}\\scoop\\apps\\python\\current\\Scripts\\pip.exe.deleteme'


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
```

This should result in upgrading pip without any error and new version of pip to be available

### Steps to Reproduce

```console
scoop install python
reg import C:\Users\{user}\scoop\apps\python\current\install-pep-514.reg
python -m pip install --upgrade --force pip
```

### Possible Solution

I think this is related to `current` folder which is symlink to the latest version folder.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
c5fce5502 (HEAD -> master, origin/master, origin/HEAD) xx-net: Update to version 5.8.6

'main' bucket:
da7fea571 (HEAD -> master, origin/master, origin/HEAD) edgedriver: Update to version 118.0.2088.76
```

### Scoop Config

```console
last_update           scoop_branch scoop_repo
-----------           ------------ ----------
10/29/2023 9:59:12 AM master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by dmiller423** [comment]
I have similar results,  there is no pip/pip3 in path,  trying to install one I get an error:
``
ERROR: Could not install packages due to an OSError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\null\\scoop\\apps\\python\\current\\Scripts\\pip.exe' -> 'C:\\Users\\null\\scoop\\apps\\python\\current\\Scripts\\pip.exe.deleteme'
``

If I visit the directory,  I find the binaries are there.. 
The junctions appears to be valid, Scripts is not making it into PATH.

That doesn't explain the above error if it's using full paths to the files however.

``
 Directory of C:\Users\null\scoop\apps\python\3.12.0\Scripts

11/14/2023  08:39 PM           108,409 pip.exe
``

So it's now installed,  or was installed and now PATH is fixed (checked in another terminal instance,  it doesn't set the variable for the current instance).  Yet it can't be updated.  

If I manually rename it to 'pip.exe.deleteme',  the update finally works in the new terminal instance.  (I only had to rename the one binary, not all 3..) 

hope this helps

**Comment by zd-dalibor** [comment]
Yes, `pip.exe` is there, but I need manually to rename it to `pip.exe.deleteme` for pip upgrade process to be successful.
Should this all happen automatically.

**Comment by rashil2000** [comment]
Hi, please see/continue the discussion here: #5090
