### ISSUE TITLE
7zip@23.01: decompress error

### ISSUE THREAD

**Issue by yep84** [ScoopInstaller/Main#5572]
I'm trying to install Gleam on Windows 10 with Scoop. Unfortunatelly without succes.

As aked, I create a new issue with the console output here:

PS C:\Users\epinyvan> scoop install gleam
WARN  Purging previous failed installation of 7zip.
ERROR '7zip' isn't installed correctly.
Removing older version (23.01).
'7zip' was uninstalled.
Installing '7zip' (23.01) [64bit] from main bucket
Loading 7z2301-x64.msi from cache
Checking hash of 7z2301-x64.msi ... ok.
Extracting 7z2301-x64.msi ... ERROR Exit code was 1618!
Failed to extract files from C:\Users\epinyvan\scoop\apps\7zip\23.01\7z2301-x64.msi.
Log file:
  ~\scoop\apps\7zip\23.01\msi.log

**Comment by HUMORCE** [comment]
This is usually caused by a msiexec process exception, go one of them:

- Restart the PC then retry.
- Switch to alternative MSI extractor: `scoop config use_lessmsi true` (Default: false)
- Resolve the msiexec exception then retry, If you know about it.

Learn more: https://learn.microsoft.com/en-us/windows/win32/msi/error-codes

**Comment by yep84** [comment]
You're totally right. Thank a lot for your answer and sorry for that quite trivial issue.
