### ISSUE TITLE
7zip@23.01: decompress error

### ISSUE THREAD

**Issue by jhessin** [ScoopInstaller/Main#5588]
I have a brand new computer that I would like to install things on using scoop, I keep getting this error when trying to install anything. I installed 7zip and git through their respective websites, but scoop can't seem to use the system versions of these. 

This is the error I'm getting. This is a brand new PC so I shouldn't be having these issues.

```
Installing '7zip' (23.01) [64bit] from main bucket
Loading 7z2301-x64.msi from cache
Checking hash of 7z2301-x64.msi ... ok.
Extracting 7z2301-x64.msi ... ERROR Exit code was 1632!
Failed to extract files from C:\Users\jhess\scoop\apps\7zip\23.01\7z2301-x64.msi.
Log file:
  ~\scoop\apps\7zip\23.01\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4023.01%3a+decompress+error
```

The issue seems to be specific to `.msi` files. I was able to install `which` without issue, but anything else seems to have issues.

**Comment by HUMORCE** [comment]
This is usually caused by a msiexec process exception, go one of them:

- Restart the PC then retry.
- Switch to alternative MSI extractor: `scoop config use_lessmsi true` (Default: false)
- Resolve the msiexec exception then retry, If you know about it.

Learn more: https://learn.microsoft.com/en-us/windows/win32/msi/error-codes
