### ISSUE TITLE
7zip@24.05: decompress error

### ISSUE THREAD

**Issue by eduardz1** [ScoopInstaller/Main#5853]
```
Installing '7zip' (24.05) [64bit] from 'main' bucket
Loading 7z2405-x64.msi from cache
Extracting 7z2405-x64.msi ... ERROR Exit code was 1618!
Failed to extract files from C:\Users\occhi\scoop\apps\7zip\24.05\7z2405-x64.msi.
Log file:
  ~\scoop\apps\7zip\24.05\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4024.05%3a+decompress+error
```

**Comment by HUMORCE** [comment]
This is usually caused by a msiexec process exception, go one of them:

- Restart the PC then retry.
- Switch to alternative MSI extractor: `scoop config use_lessmsi true` (Default: false)
- Resolve the msiexec exception then retry, If you know about it.

Learn more: https://learn.microsoft.com/en-us/windows/win32/msi/error-codes
