### ISSUE TITLE
7zip@24.07: decompress error

### ISSUE THREAD

**Issue by cycleworm** [ScoopInstaller/Main#5969]
Trying to update 7zip. I get the error which was mentioned in issue 83.  (see screenshot)
https://github.com/ScoopInstaller/Scoop/issues/83

![image](https://github.com/ScoopInstaller/Main/assets/493769/1180fdab-f822-4ae7-9b32-61324138373d)

uninstalling and installing 7zip gives the same error. 

any advice? thanks.

**Comment by cycleworm** [comment]
addition. i see error 1639 for all msi based installers. e.g. powertoys, python, ...

**Comment by EasonFP** [comment]
yes addition.
 `Updating '7zip' (24.06 -> 24.07)
Downloading new version
Loading 7z2407-x64.msi from cache
Checking hash of 7z2407-x64.msi ... ok.
Uninstalling '7zip' (24.06)
Installing '7zip' (24.07) [64bit] from 'main' bucket
Loading 7z2407-x64.msi from cache
Extracting 7z2407-x64.msi ... ERROR Exit code was 1618!
Failed to extract files from C:\Users\xxx\scoop\apps\7zip\24.07\7z2407-x64.msi.
Log file:
  ~\scoop\apps\7zip\24.07\msi.log
`

**Comment by HUMORCE** [comment]
This is usually caused by a msiexec process exception, go one of them:

- Restart the PC then retry.
- Switch to alternative MSI extractor: `scoop config use_lessmsi true` (Default: false)
- Resolve the msiexec exception then retry, If you know about it.

Learn more: https://learn.microsoft.com/en-us/windows/win32/msi/error-codes
