### ISSUE TITLE
[Request]: update llvm to 19.1.x

### ISSUE THREAD

**Issue by Arteiimis** [ScoopInstaller/Main#6226]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

LLVM

### Description

The LLVM Project is a collection of modular and reusable compiler and toolchain technologies.

### Homepage

https://github.com/llvm/llvm-project

### Download Link(s)

https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.1

### Some Indication of Popularity/Repute

It's been two weeks since llvm19.1.0 was released, hopefully scoop will update it soon!

**Comment by HUMORCE** [comment]
Upstream relied on volunteers to build binaries prior to 19.1.0, and from 19.1.0 onwards by release manager of the organization, but arm64 are not included on latest 2 versions.

Since upstream does NOT provide pre-compiled binary of arm64 for every release, LLVM arm64 is now a separate manifest: 'llvm-arm64'.

https://github.com/ScoopInstaller/Main/commit/7c5b5f7544251c0628082961043a5969ba217090 https://github.com/ScoopInstaller/Main/commit/e36b83b6437234d18809a86fff1582a643df8355
