### ISSUE TITLE
aws@2.18.9: decompress error when trying to update

### ISSUE THREAD

**Issue by sm32d** [ScoopInstaller/Main#6256]
I ran the scoop update all command and got the following error:
![image](https://github.com/user-attachments/assets/fa4a15bc-6b44-4ec8-9e3e-eafc29ee86a5)
The log file is also empty:
![image](https://github.com/user-attachments/assets/ccfaff31-475e-4d17-bef5-ebeac69894a8)

**Comment by HUMORCE** [comment]
This is usually caused by a msiexec process exception, go one of them:

- Restart the PC then retry.
- Switch to alternative MSI extractor: `scoop config use_lessmsi true` (Default: false)
- Resolve the msiexec exception then retry, If you know about it.

Learn more: https://learn.microsoft.com/en-us/windows/win32/msi/error-codes

> ERROR_INSTALL_ALREADY_RUNNING	1618	Another installation is already in progress. Complete that installation before proceeding with this install. For information about the mutex, see _MSIExecute Mutex.

**Comment by sm32d** [comment]
Hi
Thanks! It did fix itself after PC restart.

**Comment by sm32d** [comment]
Hi
Thanks! It did fix itself after PC restart.
