### ISSUE TITLE
7zip@24.08: decompress error

### ISSUE THREAD

**Issue by vikrantkadam-monocept** [ScoopInstaller/Main#6331]
Installing '7zip' (24.08) [64bit] from 'main' bucket
7z2408-x64.msi (1.9 MB) [=====================================================================================] 100%
Checking hash of 7z2408-x64.msi ... ok.
Extracting 7z2408-x64.msi ... ERROR Exit code was 1618!
Failed to extract files from C:\Users\pc\scoop\apps\7zip\24.08\7z2408-x64.msi.
Log file:
  ~\scoop\apps\7zip\24.08\msi.log

**Comment by HUMORCE** [comment]
This is usually caused by a msiexec process exception, go one of them:

- Restart the PC then retry.
- Switch to alternative MSI extractor: `scoop config use_lessmsi true` (Default: false)
- Resolve the msiexec exception then retry, If you know about it.

Learn more: https://learn.microsoft.com/en-us/windows/win32/msi/error-codes
