### ISSUE TITLE
Vim 8.2 setting $VIMRUNTIME incorrectly

### ISSUE THREAD

**Issue by rasa** [ScoopInstaller/Main#650]
Something seems to be broken here in the new 8.2, it is setting `$VIMRUNTIME` to `$HOME\scoop\apps\vim\current\vim82` but all the runtime files such as `defaults.vim` are located one directory up.  Trying to figure out a workaround right now but this is broken even without custom vimrc files.

_Originally posted by @matoro in https://github.com/ScoopInstaller/Main/pull/556#issuecomment-566061569_

**Comment by matoro** [comment]
Thanks.  This is definitely a result of the bump to 8.2 but I believe something is wrong with the packaging...just try installing stable vim and start gvim, do you see an error message pop up before it starts?

**Comment by niboan** [comment]
It's a result of unpacking the .exe installer instead of running it. Installing with the .exe installer works, The folder structure obtained when using the installer is not the same as when unpacking it.
As noted in #652, removing the vim82 directory will resolve this particular issue, but there could be other issues.
I think using the official .zip distribution files (vim82rt.zip, vim82w32.zip and gvim82.zip) would be a better approach.

Slightly off-topic: The nightlies used previously provided both 32 and 64 bit versions. The official stable distribution is 32 bit only.

**Comment by matoro** [comment]
Color schemes are still broken without the following two steps:
Copy `colors` directory to `persist\vimfiles\`
Copy `rgb.txt` to `vim82`
The former should probably be done at install time but the latter is a problem, it will not persist between upgrades.

**Comment by linsui** [comment]
@matoro By default there are only enpty directories in vimfiles. Users can always add custom color schemes into vimfiles/color and the whole vimfiles is persist. 

> You can get an rgb.txt file from any X11 distribution.  It is located in a                                              directory like "/usr/X11R6/lib/X11/".  For Vim it must be located in the                                                $VIMRUNTIME directory.  Thus the file can be found with "$VIMRUNTIME/rgb.txt".

Without `vim82` the $VIMRUNTIME is the current directory. Do we need to persist rbg.txt?

@niboan Before https://github.com/lukesampson/scoop/pull/3518 is merged we can't update multiple url.

**Comment by niboan** [comment]
> Before lukesampson/scoop#3518 is merged we can't update multiple url.

But that's just for the auto-update, the install itself will work with multiple URLs.
Since this is the stable Vim release, chances are that lukesampson/scoop#3518 is merged before the next update, and the installation will be much cleaner when using the .zip files instead of the installer .exe.

Anyway, I'll move to vim-nightly to get the 64 bit version.
