### ISSUE TITLE
rust and rustup should be msvc by default

### ISSUE THREAD

**Issue by Livven** [ScoopInstaller/Main#931]
The [official Rust download page](https://www.rust-lang.org/tools/install) links to the MSVC version. This is what how most users will be installing it so scoop should match that.

There is also a good reason for that default. See the [official explanation](https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/msvc-toolchain-support.html) (emphasis mine):

> At the release of Rust 1.0, we only supported the GNU toolchain on Windows. With the release of Rust 1.2, we introduced initial support for the MSVC toolchain. After that, as support matured, we eventually made it the default choice for Windows users.
>
> The difference between the two matters for interacting with C. If you're using a library built with one toolchain or another, you need to match that with the appropriate Rust toolchain. **If you're not sure, go with MSVC; it's the default for good reason.**

Therefore `rust` should install the MSVC version and there should be a separate `rust-gnu`. Right now it is the other way around, presumably for historical reasons. To preserve backwards compatibility, maybe start by adding `rust-gnu` and slowly move towards deprecating `rust`. The same applies to `rustup`.

Thoughts?

**Comment by rashil2000** [comment]
This will be a breaking change for a lot of users. I don't think it's worth it.

**Comment by comp500** [comment]
If the `--default-host $host_arch-pc-windows-gnu` argument is removed from the rustup install command, I think any existing install of rustup will use the host value in `persist/rustup/.rustup/settings.toml` previously set by this command - so existing installs will still use the GNU default.

I think there should at least be a warning in the `rustup`/`rust` package since the GNU toolchain is much more likely to cause linking problems with C/C++ code. It would probably also make sense to use the MSVC `rustup` build even for GNU toolchains; https://rust-lang.github.io/rustup/installation/other.html recommends you set the aforementioned `--default-host` flag instead of using the GCC build of `rustup` (see also: https://github.com/rust-lang/rustup/issues/2976#issuecomment-1094970366 https://github.com/rust-lang/rustup/issues/1851#issuecomment-492375518)

**Comment by rashil2000** [comment]
I've revisited this thread, and I think we should switch the `rust`/`rustup` manifest to be MSVC by default. 

@comp500 thanks for the detailed info. Could you make a PR for the change?

**Comment by comp500** [comment]
Should I add a `rust-gnu` manifest as well?

**Comment by rashil2000** [comment]
Yes
